generateAliasAsModel: true

################
## Docs options ##
################
packageName: Calcasa.Api
validatable: false
disallowAdditionalPropertiesIfNotPresent: false
packageVersion: 1.4.0-rc2
licenseId: Apache-2.0
packageCopyright: Copyright 2025 Calcasa B.V.
packageDescription: API client for the Calcasa Public API.
packageCompany: Calcasa
packageAuthors: Calcasa
packageTitle: Calcasa API Client
packageReleaseNotes: Add callback update and read endpoints and models.
homepage: https://calcasa.nl

