generateAliasAsModel: true

#################
## PHP options ##
#################
invokerPackage: Calcasa\Api
packageName: calcasa/api
composerPackageName: calcasa/api
# Also camelCase etc.
variableNamingConvention: snake_case
disallowAdditionalPropertiesIfNotPresent: false
licenseId: Apache-2.0
packageVersion: 0.0.2
packageCopyright: "Copyright 2021 Calcasa B.V."
packageDescription: "API client for the Calcasa Public API."
packageCompany: "Calcasa"
packageAuthors: "Calcasa"
packageTitle: Calcasa API Client
packageUrl: https://github.com/calcasa/api-php
homepage: https://calcasa.nl
excludeTests: true
