generateAliasAsModel: true

#################
## PHP options ##
#################
invokerPackage: Calcasa\Api
packageName: calcasa/api
composerPackageName: calcasa/api
# Also camelCase etc.
variableNamingConvention: camelCase
disallowAdditionalPropertiesIfNotPresent: false
legacyDiscriminatorBehavior: false
licenseName: Apache-2.0
artifactUrl: https://github.com/calcasa/api-php
artifactVersion: 1.6.0-beta4
packageCopyright: Copyright 2026 Calcasa B.V.
developerOrganization: Calcasa
developerOrganizationUrl: https://calcasa.nl
packageAuthors: Calcasa
packageTitle: Calcasa API Client
packageUrl: https://github.com/calcasa/api-php
excludeTests: true
httpUserAgent: Calcasa PHP Api Client/1.6.0-beta5
