import "@typespec/http";
import "@typespec/openapi";
import "@typespec/openapi3";
import "@typespec/versioning";

import "./operations/adressen.tsp";
import "./operations/bestemmingsplannen.tsp";
import "./operations/bodem.tsp";
import "./operations/buurt.tsp";
import "./operations/callbacks.tsp";
import "./operations/configuratie.tsp";
import "./operations/facturen.tsp";
import "./operations/fotos.tsp";
import "./operations/funderingen.tsp";
import "./operations/geldverstrekkers.tsp";
import "./operations/rapporten.tsp";
import "./operations/waarderingen.tsp";
